version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/src
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: spalacios/php_73_fpm:v.1.0.0
    volumes:
      - ./src:/var/www/html/src
      # - ~/.composer:/var/www/.composer
    networks:
      - code-network

  mysql:
    image: mysql:5.7
    env_file:
      - database.env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - code-network
    volumes:
      - ./mysql_data:/var/lib/mysql # mysql data
      - ./dumps:/dumps # para guardar dumps

networks:
  code-network:
    driver: bridge